###
POST http://127.0.0.1:8000/expenses/currency/search HTTP/1.1
content-type: application/json

{
    "code" : "AUD"
}

###
POST http://127.0.0.1:8000/expenses/category/search HTTP/1.1
content-type: application/json

{
    "ownerId": 1,
    "codes" : []
}

###
POST http://127.0.0.1:8000/expenses/account/search HTTP/1.1
content-type: application/json

{
    "ownerId": 1,
    "codes" : ["105"]
}

###
POST http://127.0.0.1:8000/expenses/transaction/search HTTP/1.1
content-type: application/json

{
    "userId": 1,
    "take" : "3",
    "offset" : "3"
}

###
POST http://127.0.0.1:8000/expenses/transaction/trycreate2 HTTP/1.1
content-type: application/json

{
    "ownerId": 1,
    "prompt" : "minimarket 35 złty Millennim 1"
}

###
POST http://127.0.0.1:8000/expenses/transaction/process HTTP/1.1
content-type: application/json

{
    "processing_user_id": 1,
    "transactions": [
    {
        "userId": 1,
        "id" : 12,
        "amount" : 90.62887,
        "accountId" : 1,
        "categoryId" : 1,
        "date" : "2024-06-01T12:00:00",
        "comment" : "testdgsa",
        "direction" : "debit",
        "active" : true
    },
    {
        "userId": 1,
        "id" : 0,
        "amount" : -1890.62887,
        "accountId" : 1,
        "categoryId" : 1,
        "date" : "2024-06-01T12:00:00",
        "comment" : "testdgs",
        "direction" : "credit",
        "active" : true
    }
    ]
}