--
-- PostgreSQL database setup generated from dump.sql
--

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- Currency
CREATE TABLE public."Currency" (
    "Id" integer NOT NULL,
    "Description" text NOT NULL,
    "Code" text NOT NULL,
    "Active" boolean DEFAULT true NOT NULL
);
ALTER TABLE public."Currency" OWNER TO postgres;
ALTER TABLE public."Currency" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Currency_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public."Currency"
    ADD CONSTRAINT "PK_Currency" PRIMARY KEY ("Id");

-- Account
CREATE TABLE public."Account" (
    "Id" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "UniqueCode" character varying(10) NOT NULL,
    "Name" text NOT NULL,
    "CurrencyId" integer NOT NULL,
    "Active" boolean DEFAULT true NOT NULL
);
ALTER TABLE public."Account" OWNER TO postgres;
ALTER TABLE public."Account" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Account_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "PK_Account" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "UQ_Account_UniqueCode" UNIQUE ("UniqueCode");
ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "CHK_Account_UniqueCode_lowercase" CHECK ("UniqueCode" = lower("UniqueCode"));
CREATE INDEX "IX_Account_CurrencyId" ON public."Account" USING btree ("CurrencyId");
ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "FK_Account_Currency_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currency"("Id") ON DELETE CASCADE;

-- Category
CREATE TABLE public."Category" (
    "Id" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "UniqueCode" character varying(10) NOT NULL,
    "Name" text NOT NULL,
    "ParentId" integer,
    "Active" boolean DEFAULT true NOT NULL
);
ALTER TABLE public."Category" OWNER TO postgres;
ALTER TABLE public."Category" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "PK_Category" PRIMARY KEY ("Id");
ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "UQ_Category_UniqueCode" UNIQUE ("UniqueCode");
ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "CHK_Category_UniqueCode_lowercase" CHECK ("UniqueCode" = lower("UniqueCode"));
CREATE INDEX "IX_Category_ParentId" ON public."Category" USING btree ("ParentId");
ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "FK_Category_Category_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."Category"("Id") ON DELETE RESTRICT;


--
-- Transfer table (new)
--
CREATE TABLE public."Transfer" (
    "Id" integer NOT NULL,
    "AccountFromId" integer NOT NULL,
    "AccountToId" integer NOT NULL
);
ALTER TABLE public."Transfer" OWNER TO postgres;
ALTER TABLE public."Transfer" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transfer_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public."Transfer"
    ADD CONSTRAINT "PK_Transfer" PRIMARY KEY ("Id");
CREATE INDEX "IX_Transfer_AccountFromId" ON public."Transfer" USING btree ("AccountFromId");
CREATE INDEX "IX_Transfer_AccountToId" ON public."Transfer" USING btree ("AccountToId");
ALTER TABLE ONLY public."Transfer"
    ADD CONSTRAINT "FK_Transfer_AccountFrom_AccountFromId" FOREIGN KEY ("AccountFromId") REFERENCES public."Account"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."Transfer"
    ADD CONSTRAINT "FK_Transfer_AccountTo_AccountToId" FOREIGN KEY ("AccountToId") REFERENCES public."Account"("Id") ON DELETE CASCADE;

-- Transaction
CREATE TABLE public."Transaction" (
    "Id" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "AccountId" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "CategoryId" integer NOT NULL,
    "TransferId" integer,
    "Comment" text,
    "Active" boolean DEFAULT true NOT NULL
);
ALTER TABLE public."Transaction" OWNER TO postgres;
ALTER TABLE public."Transaction" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transaction_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id");
CREATE INDEX "IX_Transaction_AccountId" ON public."Transaction" USING btree ("AccountId");
CREATE INDEX "IX_Transaction_CategoryId" ON public."Transaction" USING btree ("CategoryId");
CREATE INDEX "IX_Transaction_TransferId" ON public."Transaction" USING btree ("TransferId");
ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Account_AccountId" FOREIGN KEY ("AccountId") REFERENCES public."Account"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Category"("Id") ON DELETE CASCADE;
ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Transfer_TransferId" FOREIGN KEY ("TransferId") REFERENCES public."Transfer"("Id") ON DELETE SET NULL;


-- End of setup
